"""upload to

Revision ID: d339b6ccadf6
Revises: ee0e678af0fa
Create Date: 2026-08-19 14:03:37.352394

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "d339b6ccadf6"
down_revision: str | Sequence[str] | None = "ee0e678af0fa"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
