"""update members role

Revision ID: 91907f07728f
Revises: d0b3576568d5
Create Date: 2026-08-13 21:03:06.500137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_file
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '91907f07728f'
down_revision: Union[str, Sequence[str], None] = 'd0b3576568d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

project_permission_enum = postgresql.ENUM('read', 'write', name='projectpermission')

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    project_permission_enum.create(op.get_bind(), checkfirst=True)
    op.add_column(
        'project_members',
        sa.Column(
            'permission',
            project_permission_enum,
            nullable=False,
            server_default='read'  # <--- КЛЮЧЕВОЙ МОМЕНТ: Заполнит существующие строки в базе
        )
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_members', 'permission')
    project_permission_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
