"""update env.py .ini

Revision ID: d0b3576568d5
Revises: a4e0d6ae306b
Create Date: 2026-08-11 19:53:25.961531

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = 'd0b3576568d5'
down_revision: str | Sequence[str] | None = 'a4e0d6ae306b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
