"""

Revision ID: d4952e38e85c
Revises: 965f428f1d52
Create Date: 2026-08-05 14:40:59.390087

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "d4952e38e85c"
down_revision: str | Sequence[str] | None = "965f428f1d52"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
