"""fix_relationships

Revision ID: e647929037a9
Revises: 08cb40b41fd7
Create Date: 2026-08-05 00:55:44.644129

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = 'e647929037a9'
down_revision: str | Sequence[str] | None = '08cb40b41fd7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
