"""empty

Revision ID: e736743c244b
Revises: d4952e38e85c
Create Date: 2026-08-10 14:58:01.980016

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = 'e736743c244b'
down_revision: str | Sequence[str] | None = 'd4952e38e85c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
